<?php
namespace common\lib\base;

use Yii;
use yii\base\Model;
use yii\web\UploadedFile;

class UploadForm extends Model
{
    /**
     * @var UploadedFile
     */
    public $imageFile;  //POST上传上来的文件$_FILES
    private $imageName; //上传文件后的相对文件路径
    private $basePath;  //基础上传文件夹（含初始值）
    private $baseUrl;   //基础访问路径（含初始值）

    /**
     * init
     */
    public function init()
    {
        $this->basePath = $this->basePath ?: Yii::getAlias("@webroot");
        $this->baseUrl = $this->baseUrl ?: Yii::getAlias("@web");
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public function rules()
    {
        return [
            [['imageFile'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg, jepg'],
        ];
    }

    /**
     * @return bool
     */
    public function upload()
    {
        //上传认证
        if(!$this->validate())
            return false;

        //参数设置
        $date = Date("Ymd");
        $name = uniqid();
        $extension = $this->imageFile->extension;

        //保存文件
        $this->imageName = "upload/$date/$name.$extension";
        $this->mkdirs(dirname("$this->basePath/$this->imageName"));
        $this->imageFile->saveAs("$this->basePath/$this->imageName");
        return true;
    }

    /**
     * @return null
     */
    public function getFileName(){
        return $this->imageName ? "$this->basePath/$this->imageName" : null;
    }

    /**
     * @return null
     */
    public function getUrl(){
        return $this->imageName ? "$this->baseUrl/$this->imageName" : null;
    }

    /**
     * @param $path
     * @return bool
     */
    private function mkdirs($path){
        //处理相对路径
        if($path == "." || $path == "./" || empty($path))
            return true;

        //获取父路径和文件名
        $info = pathinfo($path);
        $dirname = $info['dirname'];

        //判断父路径是否存在,不存在则递归
        if(!is_dir($dirname))
            self::mkdirs($dirname);

        //检测文件夹是否存在,不存在则新建
        if(!is_dir($path))
            mkdir($path);

        //返回
        return true;
    }
}