<?php
namespace api\lib;

use Yii;
use yii\base\Event;
use yii\web\Response;
use yii\rest\ActiveController;
use yii\helpers\ArrayHelper;

/**
 * Class ApiController
 * @package api\controllers
 */
class ApiController extends ActiveController
{
    /**
     * @var string
     */
    public $modelClass = '';

    /**
     * {@inheritdoc}
     */
    public function init()
    {
        //设置response
        Yii::$app->setComponents(["response"=>['class' => 'api\lib\ApiResponse',]]);

        // TODO: Change the autogenerated stub
        parent::init();
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(),[
            //配置跨域
            'corsFilter' => [
                'class' => \yii\filters\Cors::className(),
                'cors' => [
                    'Origin' => ['*'],
                    'Access-Control-Allow-Origin' => ['*'],
                    'Access-Control-Request-Method' => ['*'],
                    'Access-Control-Request-Headers' => ['*'],
                ],
            ],
            //配置行为
            /*'apiBehavior' => [
                'class' => ApiBehavior::className(),
            ]*/
        ]);
    }
}
