<?php
namespace api\lib;

use yii\web\Response;

class ApiResponse extends Response{
    /**
     * 常量
     */
    const FORMAT_JSON = "JSON";
    const FORMAT_HTML = "HTML";

    /**
     * 参数
     */
    private $responseFormat = self::FORMAT_JSON;

    /**
     * 设置报文格式
     */
    private function setFormat(){
        switch ($this->responseFormat){
            case self::FORMAT_HTML:
                return $this->setFormatHtml();
                break;
            case self::FORMAT_JSON:
                return $this->setFormatJson();
                break;
        }
    }

    /**
     * 设置成JSON格式
     */
    private function setFormatJson(){
        $this->format = Response::FORMAT_JSON;
        $this->data = [
            'state' =>  [
                'code' => $this->isSuccessful ? 0 : $this->statusCode,
                'message' => $this->isSuccessful ? "OK" : (isset($this->data["message"])?$this->data["message"]:""),
            ],
            'data' => $this->data
        ];
        $this->statusCode = 200;
    }

    /**
     * 设置成HTML格式
     */
    private function setFormatHtml(){
        $this->format = Response::FORMAT_HTML;
    }

    /**
     * 发送报文
     */
    public function send(){
        // Set Format
        $this->setFormat();

        // TODO: Change the autogenerated stub
        return parent::send();
    }
}