<?php

namespace common\models\course;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "course_type".
 *
 * @property int $id 聚集索引
 * @property string $name 类型名
 * @property string $name_en 类型名
 * @property int $created_at 创建时间
 * @property int $updated_at 更新时间
 */
class CourseType extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'course_type';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['created_at', 'updated_at'], 'integer'],
            [['name', 'name_en'], 'string', 'max' => 50],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => '课程类型',
            'name_en' => '课程类型（英）',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
        ];
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if($insert)
            $this->created_at = time();
        $this->updated_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    static function getMap(){
        $all = self::find()->all();
        $map = [];
        foreach ($all as $model){
            $map[$model->id] = "$model->name ($model->name_en)";
        }
        return $map;
    }
}
