<?php

namespace common\models\media;

use Yii;

/**
 * This is the model class for table "pronunciation".
 *
 * @property int $id
 * @property string $word
 * @property string $audio
 * @property int $created_at
 * @property int $updated_at
 */
class Pronunciation extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pronunciation';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['word', 'audio'], 'required'],
            [['created_at', 'updated_at'], 'integer'],
            [['word'], 'string', 'max' => 50],
            [['audio'], 'string', 'max' => 250],
            [['word'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'word' => '单词',
            'audio' => '音频',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
        ];
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        //创建时间
        if($insert) $this->created_at = time();

        //更新时间
        $this->updated_at = time();

        //大小写转换
        $this->word = strtolower($this->word);

        //父函数
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
