<?php

namespace common\models\task;

use Yii;
use common\models\course\Course;
use common\models\course\CourseLesson;

/**
 * This is the model class for table "task".
 *
 * @property int $id 作业ID
 * @property int $type 作业类型
 * @property int $course_id 课程ID
 * @property int $lesson_id 章节ID
 * @property string $title 作业标题
 * @property string $content 作业内容
 * @property string $file 作文文件
 * @property string $audio 作业音频
 * @property int $create_at 创建时间
 * @property int $finish_at 结束时间
 *
 * @property Course $course
 * @property CourseLesson $lesson
 * @property TaskSubmit[] $taskSubmits
 */
class Task extends \yii\db\ActiveRecord
{
    public function init()
    {
        // TODO: Change the autogenerated stub
        parent::init();

        //设置默认值
        if($this->className() == __CLASS__){
            $this->create_at = time();
            $this->type = 0;
        }
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'task';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'course_id', 'lesson_id', 'create_at', 'finish_at'], 'integer'],
            [['course_id', 'lesson_id', 'title', 'content'], 'required'],
            [['content'], 'string'],
            [['title'], 'string', 'max' => 50],
            [['file', 'audio'], 'string', 'max' => 256],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => '类型',
            'typeName' => '类型',
            'course_id' => '课程',
            'lesson_id' => '章节',
            'title' => '标题',
            'content' => '内容',
            'file' => '文件',
            'audio' => '音频',
            'create_at' => '创建时间',
            'finish_at' => '结束时间',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCourse()
    {
        return $this->hasOne(Course::className(), ['id' => 'course_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLesson()
    {
        return $this->hasOne(CourseLesson::className(), ['id' => 'lesson_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTaskSubmits()
    {
        return $this->hasMany(TaskSubmit::className(), ['task_id' => 'id']);
    }

    /**
     * @return mixed|string
     */
    public function getTypeName(){
        $map = self::getTypeMap();
        return empty($map[$this->type]) ? "" : $map[$this->type];
    }

    /**
     * @return array
     */
    static public function getTypeMap(){
        return [
            0=>"文本",
            1=>"音频",
            2=>"文本+音频"
        ];
    }
}
